name: branch-source
on:
  workflow_call:
    inputs:
      # Acepta:
      # - feature/descripcion-descripcion
      # - feature/TICKET-123-descripcion-descripcion
      # - feature/TICKET-123/descripcion-descripcion
      feature_pattern:
        type: string
        default: '^feature\/((?:[A-Z][A-Z0-9]+-\d+[-\/])?[a-z0-9]+(?:-[a-z0-9]+)*)$'
        description: Expresión regular para validar ramas de características

      # Acepta:
      # - release/x.y.z
      release_pattern:
        type: string
        default: '^release\/[0-9]+\.[0-9]+\.[0-9]+$'
        description: Expresión regular para validar ramas de lanzamiento

      # Acepta:
      # - hotfix/x.y.z
      hotfix_pattern:
        type: string
        default: '^hotfix\/[0-9]+\.[0-9]+\.[0-9]+$'
        description: Expresión regular para validar ramas de corrección

jobs:
  branch-source:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: read

    steps:

      # Imponer reglas de origen para PR
      - name: Enforce PR source branch rules
        run: |
          // Obtener la referencia de la rama base y la rama de origen
          HEAD="${{ github.head_ref }}"
          BASE="${{ github.base_ref }}"

          // Expresiones regulares para validar ramas
          FEATURE_RE='${{ inputs.feature_pattern }}'
          RELEASE_RE='${{ inputs.release_pattern }}'
          HOTFIX_RE='${{ inputs.hotfix_pattern }}'

          // Validar ramas
          echo "[INFO] Validando origen de PR: HEAD='$HEAD' BASE='$BASE'"

          ok="false"

          case "$BASE" in
            main)
              if echo "$HEAD" | grep -Eq "$RELEASE_RE|$HOTFIX_RE"; then
                ok="true"
              fi
              ;;
            develop)
              if echo "$HEAD" | grep -Eq "$FEATURE_RE|$RELEASE_RE"; then
                ok="true"
              fi
              ;;
            *)
              # Para otras bases, no aplicamos restricción de ramas
              ok="true"
              ;;
          esac

          if [ "$ok" != "true" ]; then
            echo "[ERROR] Regla de origen incumplida:"
            echo "   - main solo acepta: release/x.y.z o hotfix/x.y.z"
            echo "   - develop acepta:   feature/<descripcion> o feature/TICKET-123-<descripcion> o release/x.y.z"
            echo "   HEAD='$HEAD'  BASE='$BASE'"
            exit 1
          fi

          echo "[SUCCESS] Origen de PR válido"
