name: branch-source
on:
  workflow_call:
    inputs:
      # Acepta:
      # - feature/descripcion-descripcion
      # - feature/TICKET-123-descripcion-descripcion
      # - feature/TICKET-123/descripcion-descripcion
      feature_pattern:
        type: string
        default: '^feature\/((?:[A-Z][A-Z0-9]+-\d+[-\/])?[a-z0-9]+(?:-[a-z0-9]+)*)$'
        description: Expresión regular para validar ramas de características

      # Acepta:
      # - release/x.y.z
      release_pattern:
        type: string
        default: '^release\/[0-9]+\.[0-9]+\.[0-9]+$'
        description: Expresión regular para validar ramas de lanzamiento

      # Acepta:
      # - hotfix/x.y.z
      hotfix_pattern:
        type: string
        default: '^hotfix\/[0-9]+\.[0-9]+\.[0-9]+$'
        description: Expresión regular para validar ramas de corrección

jobs:
  branch-source:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce PR source branch rules
        run: |
          HEAD="${{ github.head_ref }}"
          BASE="${{ github.base_ref }}"

          FEATURE_RE='${{ inputs.feature_pattern }}'
          RELEASE_RE='${{ inputs.release_pattern }}'
          HOTFIX_RE='${{ inputs.hotfix_pattern }}'

          echo "[INFO] Validando origen de PR"
          echo "   HEAD='$HEAD'"
          echo "   BASE='$BASE'"
          echo "   FEATURE_RE=$FEATURE_RE"
          echo "   RELEASE_RE=$RELEASE_RE"
          echo "   HOTFIX_RE=$HOTFIX_RE"

          ok="false"
          case "$BASE" in
            main)
              if echo "$HEAD" | grep -Eq "$RELEASE_RE|$HOTFIX_RE"; then
                ok="true"
              fi
              ;;
            develop)
              if echo "$HEAD" | grep -Eq "$FEATURE_RE|$RELEASE_RE"; then
                ok="true"
              fi
              ;;
            *)
              # Para otras bases, no aplicamos restricción
              ok="true"
              ;;
          esac

          if [ "$ok" != "true" ]; then
            echo "[ERROR] Regla de origen incumplida:"
            echo "   - main solo acepta: release/x.y.z o hotfix/x.y.z"
            echo "   - develop acepta:   feature/<descripcion> o feature/TICKET-123-<descripcion> o release/x.y.z"
            echo "   HEAD='$HEAD'  BASE='$BASE'"
            exit 1
          fi

          echo "[SUCCESS] Origen de PR válido"
