name: code-quality
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      enforce:
        description: "Si true, falla si no hay lint/test"
        type: boolean
        default: false

jobs:
  quality:
    name: Lint & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Si no hay package.json, pasar, a menos que enforce=true
      - name: Check package.json
        id: pkg
        run: |
          if [ ! -f package.json ]; then
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: steps.pkg.outputs.found == 'true'
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install
        if: steps.pkg.outputs.found == 'true'
        run: npm ci

      - name: Run formatter (prettier) if present
        if: steps.pkg.outputs.found == 'true'
        run: |
          if npm run | grep -qE 'prettier|format'; then
            npm run prettier --if-present || npm run format --if-present
          else
            echo "No formatter script."
          fi

      - name: Run lint if present
        if: steps.pkg.outputs.found == 'true'
        run: |
          if npm run | grep -q 'lint'; then
            npm run lint
          else
            echo "No lint script."
          fi

      - name: Run tests if present
        if: steps.pkg.outputs.found == 'true'
        run: |
          if npm run | grep -q 'test'; then
            npm test
          else
            echo "No test script."
          fi

      - name: Enforce presence if requested
        if: inputs.enforce == true
        run: |
          if [ "${{ steps.pkg.outputs.found }}" != "true" ]; then
            echo "No package.json found but enforce=true"; exit 1
          fi
          MISS=0
          npm run | grep -q 'lint' || { echo "Missing lint script"; MISS=1; }
          npm run | grep -q 'test' || { echo "Missing test script"; MISS=1; }
          [ $MISS -eq 0 ] || exit 1
