name: commitlint
on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      strict:
        description: "Valida TODOS los commits del PR"
        type: boolean
        default: true
      check_pr_title:
        description: "Valida el título del PR"
        type: boolean
        default: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install commitlint
        run: |
          npm i -g @commitlint/cli @commitlint/config-conventional

      - name: Create commitlint config
        run: |
          cat > commitlint.config.cjs << 'EOF'
          module.exports = {
            extends: ['@commitlint/config-conventional'],
            rules: {
              // permite acentos y evita Título Con Mayúsculas En Cada Palabra
              'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
            },
          };
          EOF

      - name: Lint PR commits (strict)
        if: ${{ inputs.strict == true && github.event_name == 'pull_request' }}
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          COMMITS=$(git log --format=%s "${BASE_SHA}..${HEAD_SHA}" || true)

          if [ -z "$COMMITS" ]; then
            echo "No commit subjects found between ${BASE_SHA}..${HEAD_SHA}"
            exit 0
          fi

          echo "Checking commits:"
          echo "$COMMITS"
          echo "$COMMITS" | npx commitlint --config commitlint.config.cjs

      - name: Lint PR title (useful for squash merge)
        if: ${{ inputs.check_pr_title == true && github.event_name == 'pull_request' }}
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $TITLE"
          echo "$TITLE" | npx commitlint --config commitlint.config.cjs
